apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kube-aci-demo
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: kube-aci-demo
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - kube-aci-demo
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: azure-vote-front
        image: microsoft/aci-helloworld
        ports:
        - containerPort: 80