apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kube-aci-demo
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: kube-aci-demo
    spec:
      containers:
      - name: kube-aci-demo
        image: microsoft/aci-helloworld
        ports:
        - containerPort: 80