apiVersion: v1
kind: Pod
metadata:
  name: init-demo-app
spec:
  containers:
  - name: nepetersv1
    image: neilpeterson/nepetersv1
    ports:
    - containerPort: 80
    volumeMounts:
    - name: workdir
      mountPath: /content
  initContainers:
  - name: init-demo-init
    image: neilpeterson/git-init-container
    command:
    - "git"
    - "clone"
    - "https://github.com/neilpeterson/kubernetes-demos.git"
    - "/content"
    volumeMounts:
    - name: workdir
      mountPath: "/content"
  volumes:
  - name: workdir
    emptyDir: {}
