apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
metadata:
  name: allow-database
spec:
  selector:
    matchLabels:
      preset: demo 
  env:
    - name: PRESET_DEMO
      value: "Demo Preset Environment Varible.."