apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
type: Opaque
data:
  azurestorageaccountname: <base64 encoded storage account name>
  azurestorageaccountkey: <base64 encoded storage account key>
---
apiVersion: v1
kind: Pod
metadata:
 name: azure-files
spec:
 containers:
  - image: neilpeterson/nepetersv1
    name: azure
    volumeMounts:
      - name: azure
        mountPath: /data
 volumes:
  - name: azure
    azureFile:
      secretName: azure-secret
      # Name of file share
      shareName: acsfileshare
      readOnly: false